import { StyleSheet } from 'react-native';
import { EXPLORE_COLORS } from './config';

const {
  panelBg,
  surfaceBg,
  border,
  label,
  white,
  accent,
  error,
  success,
} = EXPLORE_COLORS;

export const exploreStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: surfaceBg,
    paddingHorizontal: 14,
    gap: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  title: {
    color: white,
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  subtitle: {
    color: label,
    marginTop: -3,
    fontSize: 13,
  },
  headerStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: panelBg,
    gap: 8,
  },
  liveDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
  },
  statusText: {
    color: white,
    fontSize: 12,
    fontWeight: '700',
  },
  statusSubtext: {
    color: label,
    fontSize: 11,
  },
  previewCard: {
    flex: 1,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#000000',
  },
  camera: {
    flex: 1,
  },
  permissionPlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: 14,
    padding: 28,
    backgroundColor: 'rgba(22, 25, 31, 0.92)',
  },
  permissionPlaceholderText: {
    color: white,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  permissionPlaceholderSubtext: {
    color: label,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 16,
  },
  permissionButton: {
    minHeight: 50,
    paddingHorizontal: 28,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    overflow: 'hidden',
  },
  permissionButtonInner: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  permissionButtonPrimary: {
    backgroundColor: '#FFD54F',
    borderWidth: 0,
    shadowColor: '#FFD54F',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 4,
  },
  permissionButtonOutline: {
    borderWidth: 2,
    borderColor: accent,
    backgroundColor: 'rgba(27, 31, 40, 0.85)',
  },
  permissionButtonText: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  permissionButtonTextPrimary: {
    color: '#0E1015',
  },
  permissionButtonTextOutline: {
    color: accent,
  },
  previewTopBar: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  metricChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  metricChipText: {
    color: white,
    fontSize: 12,
    fontWeight: '700',
  },
  snapshotFlash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FFFFFF',
  },
  debugOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    gap: 3,
  },
  debugTitle: {
    color: '#E0F2FE',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  debugText: {
    color: '#E5E7EB',
    fontSize: 11,
    fontWeight: '600',
  },
  graphRow: {
    marginTop: 3,
    height: 36,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
  },
  graphBar: {
    flex: 1,
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  graphBarFast: {
    backgroundColor: 'rgba(34, 197, 94, 0.85)',
  },
  graphBarSlow: {
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
  },
  panel: {
    borderRadius: 16,
    backgroundColor: panelBg,
    borderWidth: 1,
    borderColor: border,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 10,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  primaryButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  startButton: {
    backgroundColor: accent,
  },
  stopButton: {
    backgroundColor: '#FBBF24',
  },
  primaryButtonText: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  iconButton: {
    minHeight: 50,
    minWidth: 92,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#1B1F28',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 8,
  },
  iconButtonText: {
    color: white,
    fontSize: 11,
    fontWeight: '700',
  },
  buttonPressed: {
    opacity: 0.78,
  },
  section: {
    gap: 8,
  },
  sectionLabel: {
    color: label,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  selectorRow: {
    flexDirection: 'row',
    gap: 8,
  },
  selectorButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#1B1F28',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  selectorButtonSelected: {
    backgroundColor: '#FDE68A',
    borderColor: '#FCD34D',
  },
  selectorButtonText: {
    color: white,
    fontSize: 13,
    fontWeight: '700',
  },
  selectorButtonTextSelected: {
    color: '#111827',
  },
  delegateRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  delegateButton: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#1B1F28',
    justifyContent: 'center',
    alignItems: 'center',
  },
  delegateButtonSelected: {
    borderColor: '#FCD34D',
    backgroundColor: '#FDE68A',
  },
  delegateButtonText: {
    color: white,
    fontSize: 11,
    fontWeight: '700',
  },
  delegateButtonTextSelected: {
    color: '#111827',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: '#1B1F28',
  },
  metaLabel: {
    color: white,
    fontSize: 12,
    fontWeight: '700',
  },
  metaStats: {
    alignItems: 'flex-end',
    flex: 1,
  },
  metaText: {
    color: label,
    fontSize: 11,
    fontWeight: '600',
  },
  errorText: {
    color: error,
    fontSize: 12,
    fontWeight: '600',
  },
  snapshotText: {
    color: '#93C5FD',
    fontSize: 11,
  },
});
